@startuml stateDiagram

state "Menú Pricipal" as main

state "Historial de Cotizaciones" as hist

state "Realizar Cotización" as cot

state "Camisa (manga)" as camMan

state "Camisa (cuello)" as camCue

state "Pantalon (chupin)" as pantChup

state "Calidad" as cal

state "Precio" as precio

state "Cantidad" as cant

state "Resultado" as res

[*] --> main
main --> hist : 1
main --> cot : 2
main --> [*] : 3
main --> main : otro
hist --> main : 3
hist --> hist : otro
cot --> camMan : 1
cot --> pantChup : 2
cot --> main : 3
cot --> cot : otro
camMan --> camCue : 1 || 2
camMan --> main : 3
camMan --> camMan : otro
camCue --> cal : 1 || 2
camCue --> main : 3
camCue --> camCue : otro
pantChup --> cal : 1 || 2
pantChup --> main : 3
pantChup --> pantChup : otro
cal --> precio : 1 || 2
cal --> main : 3
cal --> cal : otro
precio --> cant : precio > 0
precio --> precio : precio < 0
cant --> cant : cantidad > stock
cant --> res : cantidad <= stock
cant --> main : cantidad <= stock
res --> main : 3
res --> res : otro
@enduml
